/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CodeSamplesResponse {
    'nodejs'?: string;
    'dotnet'?: string;
    'python'?: string;
    'php'?: string;
    'curl'?: string;
    'ruby'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodejs",
            "baseName": "nodejs",
            "type": "string"
        },
        {
            "name": "dotnet",
            "baseName": "dotnet",
            "type": "string"
        },
        {
            "name": "python",
            "baseName": "python",
            "type": "string"
        },
        {
            "name": "php",
            "baseName": "php",
            "type": "string"
        },
        {
            "name": "curl",
            "baseName": "curl",
            "type": "string"
        },
        {
            "name": "ruby",
            "baseName": "ruby",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CodeSamplesResponse.attributeTypeMap;
    }
}

