/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StringSegment } from './stringSegment';

export class EntityTagHeaderValue {
    'tag'?: StringSegment;
    'isWeak'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tag",
            "baseName": "tag",
            "type": "StringSegment"
        },
        {
            "name": "isWeak",
            "baseName": "isWeak",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EntityTagHeaderValue.attributeTypeMap;
    }
}

