/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntityTagHeaderValue } from './entityTagHeaderValue';
import { Stream } from './stream';

export class FileStreamResult {
    'fileStream'?: Stream;
    'contentType'?: string;
    'fileDownloadName'?: string;
    'lastModified'?: Date;
    'entityTag'?: EntityTagHeaderValue;
    'enableRangeProcessing'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileStream",
            "baseName": "fileStream",
            "type": "Stream"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "fileDownloadName",
            "baseName": "fileDownloadName",
            "type": "string"
        },
        {
            "name": "lastModified",
            "baseName": "lastModified",
            "type": "Date"
        },
        {
            "name": "entityTag",
            "baseName": "entityTag",
            "type": "EntityTagHeaderValue"
        },
        {
            "name": "enableRangeProcessing",
            "baseName": "enableRangeProcessing",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return FileStreamResult.attributeTypeMap;
    }
}

