/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InvitationMetadata {
    'subId': string;
    'resultUrl': string;
    'ticketUrl': string;
    'role': string;
    'permissions'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subId",
            "baseName": "subId",
            "type": "string"
        },
        {
            "name": "resultUrl",
            "baseName": "resultUrl",
            "type": "string"
        },
        {
            "name": "ticketUrl",
            "baseName": "ticketUrl",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return InvitationMetadata.attributeTypeMap;
    }
}

