/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InvitationMetadata } from './invitationMetadata';
import { Tenant } from './tenant';

export class Invitation {
    'consumedTime'?: Date;
    'email'?: string;
    'metadata'?: InvitationMetadata;
    'id'?: string;
    'created'?: Date;
    'modified'?: Date;
    'tenant'?: Tenant;
    'tenantId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "consumedTime",
            "baseName": "consumedTime",
            "type": "Date"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "InvitationMetadata"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Date"
        },
        {
            "name": "tenant",
            "baseName": "tenant",
            "type": "Tenant"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Invitation.attributeTypeMap;
    }
}

