/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppFile } from './appFile';
import { TemplateVersionFile } from './templateVersionFile';
import { Tenant } from './tenant';

export class Report {
    'data'?: { [key: string]: any; };
    'templateFile'?: AppFile;
    'templateFileId'?: string;
    'resultFile'?: AppFile;
    'resultFileId'?: string;
    'templateVersionFile'?: TemplateVersionFile;
    'id'?: string;
    'created'?: Date;
    'modified'?: Date;
    'tenant'?: Tenant;
    'tenantId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "templateFile",
            "baseName": "templateFile",
            "type": "AppFile"
        },
        {
            "name": "templateFileId",
            "baseName": "templateFileId",
            "type": "string"
        },
        {
            "name": "resultFile",
            "baseName": "resultFile",
            "type": "AppFile"
        },
        {
            "name": "resultFileId",
            "baseName": "resultFileId",
            "type": "string"
        },
        {
            "name": "templateVersionFile",
            "baseName": "templateVersionFile",
            "type": "TemplateVersionFile"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Date"
        },
        {
            "name": "tenant",
            "baseName": "tenant",
            "type": "Tenant"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Report.attributeTypeMap;
    }
}

