/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from './tag';
import { TemplateVersionFile } from './templateVersionFile';

export class TemplateModel {
    'name'?: string;
    'id'?: string;
    'created'?: Date;
    'tags'?: Array<Tag>;
    'versions'?: { [key: string]: Array<TemplateVersionFile>; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<Tag>"
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "{ [key: string]: Array<TemplateVersionFile>; }"
        }    ];

    static getAttributeTypeMap() {
        return TemplateModel.attributeTypeMap;
    }
}

