/**
 * DocxMerge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TenantUser } from './tenantUser';

export class User {
    'id'?: string;
    'created'?: Date;
    'modified'?: Date;
    'subId'?: string;
    'email'?: string;
    'tenantUsers'?: Array<TenantUser>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Date"
        },
        {
            "name": "subId",
            "baseName": "subId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "tenantUsers",
            "baseName": "tenantUsers",
            "type": "Array<TenantUser>"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

